delimiter_ip:
  type: lookup
  size: 1
  name: IPs separator
  values:
    - _

delimiter_version:
  type: lookup
  size: 2
  name: Version Separator
  values:
    - .V

delimiter_zip:
  type: lookup
  size: 4
  name: ZIP extension
  results_name: version
  values:
    - .zip
  actions:
    - to_default_filename_version

header:
  type: lookup
  size: 2
  name: Filename Header
  values:
    - CW

receiver:
  type: alphanum_variable
  size: 3
  name: Receiver
  values:
    - 2

sender:
  type: alphanum_variable
  size: 3
  name: Sender
  values:
    - 2

sequence_n_new:
  type: numeric
  size: 4
  name: Sequence Number
  results_name: sequence_n

sequence_n_old:
  type: numeric
  size: 2
  name: Sequence Number
  results_name: sequence_n

version:
  type: numeric_float
  size: 2
  name: Version
  values:
    - 1

year:
  type: numeric
  size: 2
  name: Year
  actions:
    - to_year