groups:
  id: groups
  rule_type: group
  rules:
    - group_type: sequence
      rules:
      - rule_type: group
        id: group_info
        modifiers:
          - at_least_one

group_info:
  id: group_info
  rule_type: group
  rules:
    - group_type: sequence
      rules:
      - rule_type: record
        id: group_header
      - rule_type: group
        id: transactions
        modifiers:
          - optional
      - group_type: option
        rules:
        - rule_type: record
          id: group_trailer_base
        - rule_type: record
          id: group_trailer_short

transactions:
  id: transactions
  rule_type: group
  rules:
    - group_type: option
      rules:
      - rule_type: group
        id: agreement_transaction
      - rule_type: group
        id: work_transaction
      - rule_type: group
        id: acknowledgement_transaction
      modifiers:
        - at_least_one
        - grouped

transmission:
  id: transmission
  rule_type: group
  rules:
    - group_type: sequence
      rules:
      - rule_type: record
        id: transmission_header
      - rule_type: group
        id: groups
      - rule_type: record
        id: transmission_trailer