filename_old:
  id: filename_old
  rule_type: filename
  rules:
    - group_type: sequence
      rules:
      - rule_type: field
        id: header
        modifiers:
          - compulsory
      - rule_type: field
        id: year
        modifiers:
          - compulsory
      - rule_type: field
        id: sequence_n_old
        modifiers:
          - compulsory
      - rule_type: field
        id: sender
        modifiers:
          - compulsory
      - rule_type: field
        id: delimiter_ip
        modifiers:
          - compulsory
      - rule_type: field
        id: receiver
        modifiers:
          - compulsory
    - group_type: option
      rules:
      - group_type: sequence
        rules:
        - rule_type: field
          id: delimiter_version
          modifiers:
            - compulsory
        - rule_type: field
          id: version
          modifiers:
            - compulsory
      - group_type: sequence
        rules:
        - rule_type: field
          id: delimiter_zip
          modifiers:
            - compulsory

filename_new:
  id: filename_new
  rule_type: filename
  rules:
    - group_type: sequence
      rules:
      - rule_type: field
        id: header
        modifiers:
          - compulsory
      - rule_type: field
        id: year
        modifiers:
          - compulsory
      - rule_type: field
        id: sequence_n_new
        modifiers:
          - compulsory
      - rule_type: field
        id: sender
        modifiers:
          - compulsory
      - rule_type: field
        id: delimiter_ip
        modifiers:
          - compulsory
      - rule_type: field
        id: receiver
        modifiers:
          - compulsory
    - group_type: option
      rules:
      - group_type: sequence
        rules:
        - rule_type: field
          id: delimiter_version
          modifiers:
            - compulsory
        - rule_type: field
          id: version
          modifiers:
            - compulsory
      - group_type: sequence
        rules:
        - rule_type: field
          id: delimiter_zip
          modifiers:
            - compulsory
