- filename:
    id: filename_old
    rules:
      - sequence:
        - field:
          - header
          - compulsory
        - field:
          - year
          - compulsory
        - field:
          - sequence_n_old
          - compulsory
        - field:
          - sender
          - compulsory
        - field:
          - delimiter_ip
          - compulsory
        - field:
          - receiver
          - compulsory
      - option:
        - sequence:
          - field:
            - delimiter_version
            - compulsory
          - field:
            - version
            - compulsory
        - sequence:
          - field:
            - delimiter_zip
            - compulsory

- filename:
    id: filename_new
    rules:
      - sequence:
        - field:
          - header
          - compulsory
        - field:
          - year
          - compulsory
        - field:
          - sequence_n_new
          - compulsory
        - field:
          - sender
          - compulsory
        - field:
          - delimiter_ip
          - compulsory
        - field:
          - receiver
          - compulsory
      - option:
        - sequence:
          - field:
            - delimiter_version
            - compulsory
          - field:
            - version
            - compulsory
        - sequence:
          - field:
            - delimiter_zip
            - compulsory