#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CWR-API documentation build configuration file.

import ast
import re
import sys
import os
import datetime
from codecs import open


# -- Version number acquisition -------------------------------------------

# Regular expression for the version
_version_re = re.compile(r'__version__\s+=\s+(.*)')

# Gets the version for the source folder __init__.py file
with open('../../cwr/__init__.py', 'rb', encoding='utf-8') as f:
    version_project = f.read()
    version_project = _version_re.search(version_project).group(1)
    version_project = str(ast.literal_eval(version_project.rstrip()))


# -- Code location --------------------------------------------------------

sys.path.append(os.path.abspath('../..'))
sys.path.append(os.path.abspath('../../cwr'))


# -- General configuration ------------------------------------------------

# Sphinx extensions
#
# autodoc: generates documentation from docstrings
# intersphinx: generates links to other Sphinx-created docs
# viewcode: generates HTML from code sources
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
]

# Only reStructuredText is accepted
source_suffix = '.rst'

# The master toctree document.
master_doc = 'contents'

# Sort members by type
autodoc_member_order = 'groupwise'

# General information about the project.
project = 'CWR-API'
copyright = '%s, WESO' % datetime.datetime.now().year
authors = ['Bernardo Martinez Garrido']

# The version info for the project.
#
# Semantic version value.
version = version_project
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Custom static files folder.
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = '%s doc' % project

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
}

# List of LaTeX documents.
latex_documents = [
    (master_doc, '%s.tex' % project, '%s Documentation' % project,
     ','.join(authors), 'manual'),
]


# -- Options for manual page output ---------------------------------------

# List of manual pages.
man_pages = [
    (master_doc, project, '%s Documentation' % project,
     [','.join(authors)], 1)
]


# -- Options for Texinfo output -------------------------------------------

# List of Texinfo documents.
texinfo_documents = [
    (master_doc, project, '%s Documentation' % project,
     ','.join(authors), project, 'API library for the CWR standard format.',
     'Miscellaneous'),
]


# -- Intersphinx links ----------------------------------------------------

# Intersphinx mapping.
intersphinx_mapping = {'https://docs.python.org/': None}
