The CWR standard
----------------

The CWR file standard has been created by {{{www.cisac.org}CISAC}} as a way for publishers and societies to share
discographic information.

CWR files containing updated information are created, sent by a sending party to a receiver, and then processed before
an acknowledgement file is returned.

.. toctree::
   :maxdepth: 2

   documents

The model API
-------------

Being as it is the backbone of the library, the CWR file model API should be presented first.

.. toctree::
   :maxdepth: 2

   acknowledgement_module